name: 'PR Thank You Action'
description: 'Demo for tutorial'
author: 'Colby Fayock <hello@colbyfayock.com>'

inputs:
  VITE_API_KEY:
    description: 'vite api key'
    required: true
  VITE_APPID:
    description: 'vite api id'
    required: true
  message:
    description: 'Message that gets sent to new pull requests'
    default: 'Thank you for submitting a pull request! We will try to review this as soon as we can.'
  searchTerm:
    description: 'Term that gets search for the Tenor API'
    default: 'thank you'

runs:
  using: 'node12'
  main: 'dist/index.js'
