name: GitHub Actions Secret Example

on:
  push:
    branches: [ master ]

jobs:
  secrets-in-github-actions:
    runs-on: windows-latest

    # The Secrect Actions GitHub example has three steps
    steps:
      # Show how to print unmasked GitHub secrets to the console
      - name: Step 1 - Echo out a GitHub Actions Secret to the logs
        run: |
          echo "The GitHub Action Secret will be masked:  "
          echo ${{ secrets.VITE_API_KEY }}
          echo "Trick to echo GitHub Actions Secret:  "
          echo ${{secrets.VITE_API_KEY}} | sed 's/./& /g' 
      # Use a GitHub Actions secret variable in a bash shell
      - name: Step 2 - GitHub Action if statement (true)
        env: 
          VITE_API_KEY: ${{ secrets.VITE_API_KEY }}
