name: Test

on:
  pull_request:
    types: [opened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          API_KEY: ${{secrets.API_KEY}}
          AUTHDOMAINE: ${{secrets.AUTHDOMAINE}}
          PROJECTID: ${{secrets.PROJECTID}}
          STORAGEBUCKET: ${{secrets.STORAGEBUCKET}}
          MESSAGINGSENDERID: ${{secrets.MESSAGINGSENDERID}}
          APPID: ${{secrets.APPID}}
          MEASUREMENTID: ${{secrets.MEASUREMENTID}}
         
